program: main.o src/Interact.o src/reminder.o src/linked_list.o
	gcc -o program main.o src/Interact.o src/reminder.o src/linked_list.o -Wall -Wextra -g

main.o: main.c src/Interact.h src/reminder.h src/linked_list.h
	gcc -c main.c -Wall -Wextra -g

src/Interact.o: src/Interact.c src/reminder.h src/linked_list.h
	gcc -c src/Interact.c -Wall -Wextra -g

src/reminder.o: src/reminder.c src/reminder.h
	gcc -c src/reminder.c -Wall -Wextra -g

src/linked_list.o: src/linked_list.c src/linked_list.h
	gcc -c src/linked_list.c -Wall -Wextra -g

clean:
	rm -f *.o src/*.o program

